general:
  size: 32
  encoding: 'ASCII'
  characters:
    - from: 'a'
      to: 'z'
    - from: 'A'
      to: 'Z'
    - from: '0'
      to: '9'
render:
  from: 'data/raw'
  to: 'data/img'
  fonts: ['*']
train:
  data:
    dir: 'data/img'  # Should be the same as config['render']['to']
    basefont: 'arial'
    train: 0.8
    dev: 0.1
    seed: 2021
    batch_size: 128
    epoch: 1
  generator:
    layer: 4
  discriminator:
    layer: 4
  training:
    seed: 8000
    lr: 0.01
    epoch: 20
    iteration: 500
generate:
  basefont: 'arial'